config/routes.rb
Rails.application.routes.draw do

  # Route config for ActiveAdmin
  ActiveAdmin.routes(self)

  devise_for :users, skip: [:sessions, :passwords, :registrations, :confirmations, :invitations]

  devise_scope :user do
    post    :forgot_password,   to: "passwords#create",     as: :user_password
    get     :forgot_password,   to: "passwords#new",        as: :new_user_password
    get     :reset_password,    to: "passwords#edit",       as: :edit_user_password
    put     :reset_password,    to: "passwords#update",     as: :reset_user_password

    delete  :logout,            to: "sessions#destroy",     as: :destroy_user_session
    post    :login,             to: "sessions#create",      as: :user_session
    get     :login,             to: "sessions#new",         as: :new_user_session

    post    :signup,            to: "registrations#create",   as: :user_registration
    get     :signup,            to: "registrations#new",      as: :new_user_registration
    get     :profile,           to: "registrations#edit",     as: :edit_user_registration
    put     :profile,           to: "registrations#update",   as: :update_user_registration
    post    :regenerate_api_key,to: "registrations#regenerate_api_key", as: :regenerate_api_key

    post    :activate,          to: "confirmations#create", as: :user_confirmation
    get     :activate,          to: "confirmations#new",    as: :new_user_confirmation
    get     :confirmation,      to: "confirmations#show"

    get     :accept_invitation, to: "invitations#edit",     as: :user_invitation
    put     :accept_invitation, to: "invitations#update"
  end

  resources :users, path: :members do 
    collection do
      post :approve,        action: :approve_user
      post :disapprove,     action: :disapprove_user
      post :grant_admin,    action: :grant_admin
      post :revoke_admin,   action: :revoke_admin
    end
  end

  resources :organizations

  resources :countries do
    resources :sites
  end

  resources :sites
  # Routes for custom methods (for use with ReactJS)
  post "sites/add_role", to: "sites#add_role"
  post "sites/remove_role", to: "sites#remove_role"

  resources :languages do
    resources :articles
  end

  resources :categories

  resources :articles do
    member do
      post :publish
      post :unpublish
    end
  end

  ## API routes
  namespace :api do
    resources :users
    resources :articles
    resources :countries
    resources :categories
    resources :languages
  end

  # You can have the root of your site routed with "root"
  root 'welcome#index'
end

app/models/article.rb
# == Schema Information
#
# Table name: articles
#
#  id          :integer          not null, primary key
#  english     :text
#  phonetic    :text
#  created_at  :datetime
#  updated_at  :datetime
#  picture     :string
#  language_id :integer
#  tsv_data    :tsvector
#  category_id :integer
#  state       :string           default("draft")
#

class Article < ActiveRecord::Base
  include PgSearch

  belongs_to :language
  belongs_to :category
  has_many :audios

  accepts_nested_attributes_for :audios, reject_if: :all_blank, allow_destroy: true

  # default order when calling the Article model
  default_scope -> { order('created_at DESC') }
  default_value_for :state, 0

  # CarrierWave integration for uploading pictures
  mount_uploader :picture, PictureUploader

  validates :picture, presence: true

  # PgSearch
  pg_search_scope :article_search,
                  against: :tsv_data,
                  using: {
                      tsearch: {
                          dictionary: 'english',
                          any_word: true,
                          prefix: true,
                          tsvector_column: 'tsv_data'
                      }
                  }

  enum state:   [:draft, :published]
end

app/controllers/api/articles_controller.rb
class API::ArticlesController < API::BaseController
  include StrongParams

  def index
    authorize_user! :read, Article

    if params[:q].blank?
      @records = Article.page(params[:page]).per(20)
    else
      @records = Article.article_search(params[:q]).page(params[:page]).per(20)
    end

    respond_with(@records) do |format|
      format.json { render json: @records, root: :articles }
    end
  end

  def show
    authorize_user! :read, Article

    @record = Article.find(params[:id])

    respond_with(@record) do |format|
      format.json { render json: @record, root: :article }
    end
  end

  def create
    authorize_user! :create, Article

    @record = Article.new(article_params)

    respond_with(@record) do |format|
      if @record.save
        format.json { render json: @record, root: :article, status: :created }
      else
        format.json { render json: { errors: @record.errors.to_hash(true) }, status: :unprocessable_entity }
      end
    end
  end

  def update
    authorize_user! :update, Article

    @record = Article.find(params[:id])

    respond_with(@record) do |format|
      if @record.update(article_params)
        format.json { render json: @record, root: :article }
      else
        format.json { render json: { errors: @record.errors.to_hash(true) }, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    authorize_user! :destroy, Article

    @record = Article.find(params[:id])

    respond_with(@record) do |format|
      if @record.destroy
        format.json { render json: {  article: {id: @record.id, deleted: true} } }
      else
        format.json { render json: { errors: @record.errors.to_hash(true) }, status: :unprocessable_entity }
      end
    end
  end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  include StrongParams

  before_action :set_article, only: [:show, :edit, :update, :destroy, :publish, :unpublish]

  load_and_authorize_resource

  respond_to :html, :json

  def new
    @article = Article.new
    @article.audios.build
    @categories = Category.all
  end

  def index
    if params[:q].blank?
      @articles = Article.includes(:category, :language).page(params[:page]).per(20)
    else
      @articles = Article.includes(:category, :language).article_search(params[:q]).page(params[:page]).per(20)
    end
  end

  def create
    @article = Article.new(article_params)

    if @article.save
      redirect_to @article
    else
      @categories = Category.all
      render 'new'
    end
  end

  def edit
    @categories = Category.all
  end

  def destroy
    @article.destroy

    redirect_to articles_path
  end

  def show
  end

  def update
    if @article.update(article_params)
      redirect_to @article
    else
      @categories = Category.all
      render 'edit'
    end
  end

  def publish
    respond_with(@article) do |format|
      if @article.published!
        flash[:notice] = "The article has been published."

        format.html { redirect_to article_path(@article) }
        format.json { render json: @article, location: article_path(@article) }
      else
        flash[:error] = "Failed to publish the article, please try again."

        format.html { redirect_to article_path(@article) }
        format.json { render json: @article.errors.to_hash(true), status: :unprocessable_entity }
      end
    end
  end

  def unpublish
    respond_with(@article) do |format|
      if @article.draft!
        flash[:notice] = "The article has been drafted."

        format.html { redirect_to article_path(@article) }
        format.json { render json: @article, location: article_path(@article) }
      else
        flash[:error] = "Failed to draft the article, please try again."

        format.html { redirect_to article_path(@article) }
        format.json { render json: @article.errors.to_hash(true), status: :unprocessable_entity }
      end
    end
  end

  private
  def set_article
    @article = Article.includes(:category, :language, :audios).find(params[:id])
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_article.html.erb
<li>
    <ul class="CardListTableRow">

        <li class="CardListTable-cal u-w180px" data-th="Picture">
            <div class="CardListTable-content">
                <%= link_to image_tag(article.picture_url, width: 50), article_path(article) if article.picture.present? %>
            </div>
        </li>

        <li class="CardListTable-cal u-w180px" data-th="English Text">
            <div class="CardListTable-content">
                <%= article.english %>
            </div>
        </li>

        <li class="CardListTable-cal u-w180px" data-th="Phonetic Text">
            <div class="CardListTable-content">
                <%= article.phonetic %>
            </div>
        </li>

        <li class="CardListTable-cal u-w180px" data-th="Category">
            <div class="CardListTable-content">
                <%= article.category.try(:name) %>
            </div>
        </li>

        <li class="CardListTable-cal u-w180px" data-th="Language">
            <div class="CardListTable-content">
                <% if article.language.present? %>
                    <%= article.language.name %>
                <% end %>
            </div>
        </li>

        <% if can? :update, article %>
            <li class="CardListTable-cal CardListTable-cal--noheading u-w60px tar" data-th="Action">
                <div class="CardListTable-content">
                    <div class="dropdown">
                        <a data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" class="button--icon" href="#"><i class="icon-action"></i></a>
                        <ul class="dropdown-menu u-rightPopup">
                            <li>
                                <%= link_to 'Edit', edit_article_path(article) %>
                            </li>
                            <% if can? :destroy, article %>
                                <li>
                                    <%= link_to 'Delete', article_path(article), method: :delete, data: { confirm: 'Are you sure?' } %>
                                </li>
                            <% end %>
                        </ul>
                    </div>
                </div>
            </li>
        <% end %>

    </ul>
</li>

app/views/articles/_form.html.erb
<%= form_for @article, html: {class: "Form--dual", id: "_form"} do |f| %>

    <%= render partial: "shared/error_messages", object: @article %>

    <div class="Form--dualDivider">
        <div class="g--half">

            <div class="Form-group">
                <%= f.label :picture %>
                <%= image_tag(@article.picture_url) if @article.picture.present? %>
                <%= f.file_field :picture, class: "Form-control" %>

                <% if @article.picture.present? %>
                    <span class="help-inline">( If you wish to change the picture, click on browse and upload the new file.)</span>
                <% end %>
            </div>

            <div class="Form-group">
                <%= f.label :language_id, "Language" %>
                <div>
                    <% if current_user.has_any_role? :superadmin, :admin, {name: :volunteer, resource: :any} %>
                        <%= f.collection_select(:language_id, Language.all, :id, :name, {}, {class: "Form-control"}) %>
                    <% elsif current_user.has_role? :contributor, :any %>
                        <%= f.collection_select(:language_id, Language.where(name: current_user.lang), :id, :name, {}, {class: "Form-control"}) %>
                    <% end %>
                </div>
            </div>

            <div class="Form-group">
                <%= f.label :category %>
                <%= f.collection_select(:category_id, @categories, :id, :name, {}, {class: "Form-control"}) %>
            </div>

            <div class="Form-group">
                <%= f.label :english, "English Text" %>
                <%= f.text_field :english, class: "Form-control" %>
            </div>

            <div class="Form-group">
                <%= f.label :phonetic, "Phonetic Text" %>
                <%= f.text_field :phonetic, class: "Form-control" %>
            </div>

            <% if can?(:delete, Article) %>
                <div class="Form-group">
                    <%= f.label :state, "Publish" %>
                    <%= f.select :state, [["Unpublish", 'draft'], ['Publish', 'published']], {}, class: "Form-control" %>
                </div>
            <% end %>

        </div>

        <div class="g--half g--last">

          <h3>Audio Translations</h3>

            <div class="clear">
              <div class="g--half">
                <div class="Form-group">
                  <%= label_tag "Text" %>
                </div>
              </div>

              <div class="g--half g--last">
                <div class="Form-group">
                  <%= label_tag "Audio File" %>
                </div>
              </div>
              <div class="clear"></div>
            </div>

          <div class="AudioContainer">
              <%= f.fields_for :audios do |audio|%>
                <div class="clear audioBox">
                  <div class="g--half">
                    <div class="Form-group">
                      <%= audio.text_field :content, class: "Form-control" %> 
                    </div>
                  </div>

                  <div class="g--half g--last">
                    <div class="Form-group">
                      <%= audio.file_field :audio, class: "Form-control Media--file" %> 
                      <%= audio.check_box :_destroy, class: "Form-control hide" %> 
                      <a href="#" class="Close Close--cross u-fr removeAudioFile"><span class="icon-close"></span></a>
                    </div>
                  </div>
                  <div class="clear"></div>
                </div>
              <% end %>
          </div>

          <a href="#" class="addMoreAudio">Add More</a>

        </div>
    </div>
<% end %>

app/views/articles/_search_form.html.erb
<div class="row">
    <div class="span8 search">
        <form class="form-search" action="" method='get'>
            <%= text_field_tag :q, params[:search], id: 'search_field', class: 'input-medium search-query'  %>
            <button class="btn btn-default btn-xs" type="submit">Search</button>
        </form>
    </div>
</div>

<hr />

app/views/articles/edit.html.erb
<header class="app-bar promote-layer">
    <div class="app-bar-container">

        <button class="menu"><span class="icon-menu"></span></button>

        <div class="Heading">
            <%= link_to articles_path, class: "Back" do %>
                <span class="icon-chevron-left-thin"></span><span class="Back-text">Back</span>
            <% end %>
            <h1 class="title"><span>Editing Article</span></h1>
        </div>

        <ul class="app-bar-actions">
            <li>
                <button class="button button--primary" form="_form">Submit</button>
            </li>
        </ul>

    </div>
</header>

<main>
    <div class="Form u-pushTopBottom clear">
        <%= render 'form' %>
        <div class="clear"></div>
    </div>
</main>

app/views/articles/index.html.erb
<header class="app-bar promote-layer">
    <div class="app-bar-container">
        <button class="menu"><span class="icon-menu"></span></button>

        <div class="Heading">
            <h1 class="title"><span>Articles</span></h1>
        </div>
    </div>
</header>
<main>
    <div class="AppControls">
        <div class="AppControls--box AppControls-left">
            <form class="Form Form--inline AppControls-search" method='get'>
                <div class="Form-group">
                    <input type="search" class="Form-control" name="q" id="search" placeholder="Search Articles" />
                </div>
                <button type="submit" class="btn btn-default icon-search">Search</button>
            </form>
        </div>

        <div class="AppControls--box AppControls-middle"></div>

        <div class="AppControls--box AppControls-right">
            <a class="button--icontext button--ricontext" href="<%= new_article_path %>"><i class="icon-plus"></i> <span>New Photo</span></a>
        </div>
    </div>

    <div class="CardListTable">
        <ul class="CardListTable-body">
            <%= render partial: 'article', collection: @articles %>
        </ul>
    </div>

    <%= paginate @articles %>
</main>

app/views/articles/index.js.erb
<% unless @articles.empty? %>
$("#articles").append("<%= raw escape_javascript(render(:partial => 'article', collection: @articles)) %>");
<% end %>

app/views/articles/new.html.erb
<header class="app-bar promote-layer">
    <div class="app-bar-container">

        <button class="menu"><span class="icon-menu"></span></button>

        <div class="Heading">
            <%= link_to articles_path, class: "Back" do %>
                <span class="icon-chevron-left-thin"></span><span class="Back-text">Back</span>
            <% end %>
            <h1 class="title"><span>New Article</span></h1>
        </div>

        <ul class="app-bar-actions">
            <li>
                <button class="button button--primary" form="_form">Submit</button>
            </li>
        </ul>

    </div>
</header>

<main>
    <div class="Form u-pushTopBottom clear">
        <%= render 'form' %>
        <div class="clear"></div>
    </div>
</main>

app/views/articles/show.html.erb
<header class="app-bar promote-layer">
    <div class="app-bar-container">
        <button class="menu"><span class="icon-menu"></span></button>

        <div class="Heading">
            <%= link_to articles_path, class: "Back" do %>
                <span class="icon-chevron-left-thin"></span><span class="Back-text">Back</span>
            <% end %>
            <h1 class="title"><span>Articles</span></h1>
        </div>

    </div>
</header>

<main>
  <div class="Form u-pushTopBottom clear">
      <div class="g--half">
        <%= image_tag(@article.picture_url) if @article.picture.present? %>
      </div>

      <div class="g--half g--last">
        <dl class="Info">
          <dt>Phonetic Text</dt>
          <dd><%= @article.phonetic.present? ? @article.phonetic : "N/A" %>  <%= link_to 'Edit', edit_article_path(@article), class: "Info-more" %></dd>

          <dt>English Text</dt>
          <dd><%= @article.english.present? ? @article.english : "N/A" %></dd>

          <dt>Category</dt>
          <dd><%= @article.category.try(:name).present? ? @article.category.try(:name) : "N/A" %></dd>

          <dt>Language</dt>
          <dd><%= @article.language.present? ? @article.language.name : "N/A"  %></dd>
      </dl>

      <% if can?(:delete, @article) && @article.draft? %>
        <%= link_to 'Publish', publish_article_path(@article), method: :post %>
      <% else %>
        <%= link_to 'Unpublish', unpublish_article_path(@article), method: :post %>
      <% end %>

      <h3 class="u-pushTop20">Audio Translations</h3>

      <dl class="Info">
        <% @article.audios.each do |audio| %>
          <% if audio.audio.present? %>
            <dt><%= audio.content %></dt>
            <dd>
              <%= link_to image_tag("icons/audio_icon.png", width: 24), "#", class: "jpayAudio" %>
              <%= audio_tag audio.audio %>
            </dd>
          <% end %>
        <% end %>
      </dl>
    </div>

    </div>
</main>