config/routes.rb
Rails.application.routes.draw do

  # Route config for ActiveAdmin
  ActiveAdmin.routes(self)

  devise_for :users, skip: [:sessions, :passwords, :registrations, :confirmations, :invitations]

  devise_scope :user do
    post    :forgot_password,   to: "passwords#create",     as: :user_password
    get     :forgot_password,   to: "passwords#new",        as: :new_user_password
    get     :reset_password,    to: "passwords#edit",       as: :edit_user_password
    put     :reset_password,    to: "passwords#update",     as: :reset_user_password

    delete  :logout,            to: "sessions#destroy",     as: :destroy_user_session
    post    :login,             to: "sessions#create",      as: :user_session
    get     :login,             to: "sessions#new",         as: :new_user_session

    post    :signup,            to: "registrations#create",   as: :user_registration
    get     :signup,            to: "registrations#new",      as: :new_user_registration
    get     :profile,           to: "registrations#edit",     as: :edit_user_registration
    put     :profile,           to: "registrations#update",   as: :update_user_registration
    post    :regenerate_api_key,to: "registrations#regenerate_api_key", as: :regenerate_api_key

    post    :activate,          to: "confirmations#create", as: :user_confirmation
    get     :activate,          to: "confirmations#new",    as: :new_user_confirmation
    get     :confirmation,      to: "confirmations#show"

    get     :accept_invitation, to: "invitations#edit",     as: :user_invitation
    put     :accept_invitation, to: "invitations#update"
  end

  resources :users, path: :members do 
    collection do
      post :approve,        action: :approve_user
      post :disapprove,     action: :disapprove_user
      post :grant_admin,    action: :grant_admin
      post :revoke_admin,   action: :revoke_admin
    end
  end

  resources :organizations

  resources :countries do
    resources :sites
  end

  resources :sites
  # Routes for custom methods (for use with ReactJS)
  post "sites/add_role", to: "sites#add_role"
  post "sites/remove_role", to: "sites#remove_role"

  resources :languages do
    resources :articles
  end

  resources :categories

  resources :articles do
    member do
      post :publish
      post :unpublish
    end
  end

  ## API routes
  namespace :api do
    resources :users
    resources :articles
    resources :countries
    resources :categories
    resources :languages
  end

  # You can have the root of your site routed with "root"
  root 'welcome#index'
end

app/models/country.rb
# == Schema Information
#
# Table name: countries
#
#  id              :integer          not null, primary key
#  name            :string
#  created_at      :datetime
#  updated_at      :datetime
#  organization_id :integer
#  user_id         :integer
#

class Country < ActiveRecord::Base
  belongs_to :organization
  belongs_to :user
  has_many :sites, dependent: :destroy

  validates_presence_of :name, :organization_id
end

app/controllers/countries_controller.rb
class CountriesController < ApplicationController
  load_and_authorize_resource

  def index
    if current_user.has_role? :superadmin
      @countries = Country.all.page(params[:page]).per(20)
    else
      @countries = current_user.organization.countries.page(params[:page]).per(20)
    end
  end

  def show
    @country = Country.find(params[:id])
  end

  def new
    @country = Country.new
  end

  def edit
    @country = Country.find(params[:id])
  end

  def create
    @country = Country.new(country_params)
    @country.organization_id = current_user.organization.id

    if @country.save
      redirect_to @country
    else
      render 'new'
    end
  end

  def update
    @country = Country.find(params[:id])

    if @country.update(country_params)
      redirect_to @country
    else
      render 'edit'
    end
  end

  def destroy
    @country = Country.find(params[:id])
    @country.destroy

    redirect_to countries_path
  end

  private
  # Never trust parameters from the scary internet, only allow the white list through.
  def country_params
    params.require(:country).permit(:name, :user_id, :organization_id)
  end
end

app/helpers/countries_helper.rb
module CountriesHelper
end

app/views/countries/_form.html.erb
<%= form_for @country, html: {class: "Form--dual", id: "_form"} do |f| %>
    <%= render partial: "shared/error_messages", object: @country %>

    <div class="Form--dualDivider">
        <div class="g--half">
            <div class="Form-group">
                <%= f.label :organization_id, "Organization" %>
                <%= f.collection_select(:organization_id, Organization.all, :id, :name, {prompt: true}, {class: "Form-control"}) %>
            </div>

            <div class="Form-group">
                <%= f.label :name %>
                <%= f.text_field :name, class: "Form-control" %>
            </div>

            <div class="form-group">
                <%= f.label :user_id, "Manager" %>
                <%= f.collection_select(:user_id, User.with_any_role(:superadmin, :admin), :id, :username, {prompt: true}, {class: "Form-control"}) %>
            </div>
        </div>
    </div>
<% end %>

app/views/countries/edit.html.erb
<header class="app-bar promote-layer">
    <div class="app-bar-container">
        <button class="menu"><span class="icon-menu"></span></button>

        <div class="Heading">
            <%= link_to countries_path, class: "Back" do %>
                <span class="icon-chevron-left-thin"></span><span class="Back-text">Back</span>
            <% end %>
            <h1 class="title"><span>Editing Country</span></h1>
        </div>

        <ul class="app-bar-actions">
            <li>
                <button class="button button--primary" form="_form">Submit</button>
            </li>
        </ul>

    </div>
</header>

<main>
    <div class="Form u-pushTopBottom clear">
        <%= render 'form' %>
        <div class="clear"></div>
    </div>
</main>

app/views/countries/index.html.erb
<header class="app-bar promote-layer">
    <div class="app-bar-container">
        <button class="menu"><span class="icon-menu"></span></button>

        <div class="Heading">
            <h1 class="title"><span>Countries</span></h1>
        </div>
    </div>
</header>
<main>
    <div class="AppControls">
        <div class="AppControls--box AppControls-left">
            <form class="Form Form--inline AppControls-search">
                <div class="Form-group">
                    <input type="search" class="Form-control" id="search" placeholder="Search Country" />
                </div>
                <button type="submit" class="btn btn-default icon-search">Search</button>
            </form>
        </div>

        <div class="AppControls--box AppControls-middle"></div>

        <div class="AppControls--box AppControls-right">
            <a class="button--icontext button--ricontext" href="<%= new_country_path %>"><i class="icon-plus"></i> <span>New Country</span></a>
        </div>
    </div>

    <div class="CardListTable">
        <ul class="CardListTable-body">

            <% @countries.each do |country| %>
                <li>
                    <ul class="CardListTableRow">
                        <li class="CardListTable-cal u-w30px" data-th="#">
                            <div class="CardListTable-content">
                                <%= link_to country.id, country_path(country) %>
                            </div>
                        </li>

                        <li class="CardListTable-cal u-w180px" data-th="Organization">
                            <div class="CardListTable-content">
                                <%= country.organization.name %>
                            </div>
                        </li>

                        <li class="CardListTable-cal u-w130px" data-th="Country">
                            <div class="CardListTable-content">
                                <%= country.name %>
                            </div>
                        </li>

                        <li class="CardListTable-cal u-w130px"  data-th="Manager">
                            <div class="CardListTable-content">
                                <%= link_to country.user.username, user_path(country.user) if (country.user) %>
                            </div>
                        </li>

                        <% if can? :update, country %>
                            <li class="CardListTable-cal CardListTable-cal--noheading u-w60px tar" data-th="Action">
                                <div class="CardListTable-content">
                                    <div class="dropdown">
                                        <a data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" class="button--icon" href="#"><i class="icon-action"></i></a>
                                        <ul class="dropdown-menu u-rightPopup">
                                            <li>
                                                <%= link_to 'Edit', edit_country_path(country) %>
                                            </li>
                                            <% if can? :destroy, country %>
                                                <li>
                                                    <%= link_to 'Delete', country_path(country), method: :delete, data: {confirm: 'Are you sure?'} %>
                                                </li>
                                            <% end %>
                                        </ul>
                                    </div>
                                </div>
                            </li>
                        <% end %>

                    </ul>
                </li>
            <% end %>
        </ul>
    </div>

    <%= paginate @countries %>
</main>

app/views/countries/new.html.erb
<header class="app-bar promote-layer">
    <div class="app-bar-container">

        <button class="menu"><span class="icon-menu"></span></button>

        <div class="Heading">
            <%= link_to countries_path, class: "Back" do %>
                <span class="icon-chevron-left-thin"></span><span class="Back-text">Back</span>
            <% end %>
            <h1 class="title"><span>New Country</span></h1>
        </div>

        <ul class="app-bar-actions">
            <li>
                <button class="button button--primary" form="_form">Submit</button>
            </li>
        </ul>

    </div>
</header>

<main>
    <div class="Form u-pushTopBottom clear">
        <%= render 'form' %>
        <div class="clear"></div>
    </div>
</main>

app/views/countries/show.html.erb
<header class="app-bar promote-layer">
    <div class="app-bar-container">
        <button class="menu"><span class="icon-menu"></span></button>

        <div class="Heading">
            <%= link_to countries_path, class: "Back" do %>
                <span class="icon-chevron-left-thin"></span><span class="Back-text">Back</span>
            <% end %>
            <h1 class="title"><span>Country</span></h1>
        </div>

    </div>
</header>

<main>
    <div class="Form u-pushTopBottom clear">
        <div class="g--half">

            <h3 class="title">Country #<%= @country.id %></h3>

            <dl class="Info">
                <dt>Organization</dt>
                <dd>
                    <%= @country.organization.name %>
                    <% if can? :update, @country %>
                        <%= link_to 'Edit', edit_country_path(@country), class: "Info-more" %>
                    <% end %>
                </dd>

                <dt>Name</dt>
                <dd>
                    <%= @country.name.blank? ? "N/A" : @country.name %>
                </dd>

                <% if @country.user %>
                    <dt>Manager</dt>
                    <dd>
                        <%= link_to @country.user.username, user_path(@country.user) %>
                    </dd>
                <% end %>
            </dl>

            <h3 class="title u-push2xTop">Sites</h3>

            <dl class="Info">
                <% @country.sites.reverse.each do |site| %>
                    <dt>#<%= site.id %></dt>
                    <dd><%= site.name %></dd>
                <% end %>
            </dl>

        </div>

        <div class="clear"></div>
    </div>
</main>