config/routes.rb
Rails.application.routes.draw do

  # Route config for ActiveAdmin
  ActiveAdmin.routes(self)

  devise_for :users, skip: [:sessions, :passwords, :registrations, :confirmations, :invitations]

  devise_scope :user do
    post    :forgot_password,   to: "passwords#create",     as: :user_password
    get     :forgot_password,   to: "passwords#new",        as: :new_user_password
    get     :reset_password,    to: "passwords#edit",       as: :edit_user_password
    put     :reset_password,    to: "passwords#update",     as: :reset_user_password

    delete  :logout,            to: "sessions#destroy",     as: :destroy_user_session
    post    :login,             to: "sessions#create",      as: :user_session
    get     :login,             to: "sessions#new",         as: :new_user_session

    post    :signup,            to: "registrations#create",   as: :user_registration
    get     :signup,            to: "registrations#new",      as: :new_user_registration
    get     :profile,           to: "registrations#edit",     as: :edit_user_registration
    put     :profile,           to: "registrations#update",   as: :update_user_registration
    post    :regenerate_api_key,to: "registrations#regenerate_api_key", as: :regenerate_api_key

    post    :activate,          to: "confirmations#create", as: :user_confirmation
    get     :activate,          to: "confirmations#new",    as: :new_user_confirmation
    get     :confirmation,      to: "confirmations#show"

    get     :accept_invitation, to: "invitations#edit",     as: :user_invitation
    put     :accept_invitation, to: "invitations#update"
  end

  resources :users, path: :members do 
    collection do
      post :approve,        action: :approve_user
      post :disapprove,     action: :disapprove_user
      post :grant_admin,    action: :grant_admin
      post :revoke_admin,   action: :revoke_admin
    end
  end

  resources :organizations

  resources :countries do
    resources :sites
  end

  resources :sites
  # Routes for custom methods (for use with ReactJS)
  post "sites/add_role", to: "sites#add_role"
  post "sites/remove_role", to: "sites#remove_role"

  resources :languages do
    resources :articles
  end

  resources :categories

  resources :articles do
    member do
      post :publish
      post :unpublish
    end
  end

  ## API routes
  namespace :api do
    resources :users
    resources :articles
    resources :countries
    resources :categories
    resources :languages
  end

  # You can have the root of your site routed with "root"
  root 'welcome#index'
end

app/models/category.rb
# == Schema Information
#
# Table name: categories
#
#  id         :integer          not null, primary key
#  name       :string
#  created_at :datetime
#  updated_at :datetime
#

class Category < ActiveRecord::Base
  has_many :articles

  validates :name, presence: true

  # default order when calling the Category model
  default_scope -> { order('created_at DESC') }
end

app/controllers/api/categories_controller.rb
class API::CategoriesController < API::BaseController

  def index
    authorize_user! :read, Category

    @records = Category.page(params[:page]).per(20)

    respond_with(@records) do |format|
      format.json { render json: @records, root: :categories }
    end
  end

  def show
    authorize_user! :read, Category

    @record = Category.find(params[:id])

    respond_with(@record) do |format|
      format.json { render json: @record, root: :category }
    end
  end

  def create
    authorize_user! :create, Category

    @record = Category.new(category_params)

    respond_with(@record) do |format|
      if @record.save
        format.json { render json: @record, root: :category, status: :created }
      else
        format.json { render json: { errors: @record.errors.to_hash(true) }, status: :unprocessable_entity }
      end
    end
  end

  def update
    authorize_user! :update, Category

    @record = Category.find(params[:id])

    respond_with(@record) do |format|
      if @record.update(category_params)
        format.json { render json: @record, root: :category }
      else
        format.json { render json: { errors: @record.errors.to_hash(true) }, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    authorize_user! :destroy, Category

    @record = Category.find(params[:id])

    respond_with(@record) do |format|
      if @record.destroy
        format.json { render json: {  category: {id: @record.id, deleted: true} } }
      else
        format.json { render json: { errors: @record.errors.to_hash(true) }, status: :unprocessable_entity }
      end
    end
  end

  private
  def category_params
    params.require(:category).permit(:name)
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource
  respond_to :html

  def index
    @categories = Category.page(params[:page]).per(20)

    respond_with(@categories)
  end

  def show
    respond_with(@product) do |format|
      format.html { render nothing: true }
    end
  end

  def new
    @category = Category.new

    respond_with(@category)
  end

  def edit
  end

  def create
    @category = Category.new(category_params)

    respond_with(@category) do |format|
      if @category.save
        flash[:notice] = "Category successfully created."
        format.html { redirect_to edit_category_path(@category) }
      else
        flash[:error] = "Sorry, failed to create category due to errors."
        format.html { render 'new' }
      end
    end
  end

  def update
    @category = Category.find(params[:id])

    respond_with(@category) do |format|
      if @category.update(category_params)
        flash[:notice] = "Category successfully updated."
        format.html { redirect_to edit_category_path(@category) }
      else
        flash[:error] = "Sorry, failed to update category due to errors."
        format.html { render 'edit' }
      end
    end
  end

  def destroy
    @category.destroy

    flash[:notice] = "Category has been deleted."
    respond_with(@category)
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_category
    @category = Category.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def category_params
    params.require(:category).permit(:name)
  end
end

app/views/categories/_form.html.erb
<%= form_for @category, html: {class: "Form--dual", id: "_form"} do |f| %>

    <%= render partial: "shared/error_messages", object: @category %>

    <div class="Form--dualDivider">
        <div class="g--half">

            <div class="Form-group">
                <%= f.label :name, "Name" %>
                <%= f.text_field :name, class: "Form-control" %>
            </div>

        </div>
    </div>
<% end %>

app/views/categories/edit.html.erb
<header class="app-bar promote-layer">
    <div class="app-bar-container">

        <button class="menu"><span class="icon-menu"></span></button>

        <div class="Heading">
            <%= link_to categories_path, class: "Back" do %>
                <span class="icon-chevron-left-thin"></span><span class="Back-text">Back</span>
            <% end %>
            <h1 class="title"><span>Editing Category</span></h1>
        </div>

        <ul class="app-bar-actions">
            <li>
                <button class="button button--primary" form="_form">Submit</button>
            </li>
        </ul>

    </div>
</header>

<main>
    <div class="Form u-pushTopBottom clear">
        <%= render 'form' %>
        <div class="clear"></div>
    </div>
</main>

app/views/categories/index.html.erb
<header class="app-bar promote-layer">
    <div class="app-bar-container">
        <button class="menu"><span class="icon-menu"></span></button>

        <div class="Heading">
            <h1 class="title"><span>Categories</span></h1>
        </div>
    </div>
</header>

<main>
    <div class="AppControls">
        <div class="AppControls--box AppControls-left">
            <form class="Form Form--inline AppControls-search">
                <div class="Form-group">
                    <input type="search" class="Form-control" id="search" placeholder="Search Categories" />
                </div>
                <button type="submit" class="btn btn-default icon-search">Search</button>
            </form>
        </div>

        <div class="AppControls--box AppControls-middle"></div>

        <div class="AppControls--box AppControls-right">
            <a class="button--icontext button--ricontext" href="<%= new_category_path %>"><i class="icon-plus"></i> <span>New Category</span></a>
        </div>
    </div>

    <div class="CardListTable">
        <ul class="CardListTable-body">

            <% @categories.each do |category| %>
                <li>
                    <ul class="CardListTableRow">
                        <li class="CardListTable-cal u-w30px" data-th="#">
                            <div class="CardListTable-content">
                                <% if can? :update, category %>
                                    <%= link_to category.id, edit_category_path(category) %>
                                <% else %>
                                    <%= category.id %>
                                <% end %>
                            </div>
                        </li>

                        <li class="CardListTable-cal u-w300px" data-th="Name">
                            <div class="CardListTable-content">
                                <%= category.name %>
                            </div>
                        </li>

                        <% if can? :update, category %>
                            <li class="CardListTable-cal CardListTable-cal--noheading u-w60px tar" data-th="Action">
                                <div class="CardListTable-content">
                                    <div class="dropdown">
                                        <a data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" class="button--icon" href="#"><i class="icon-action"></i></a>
                                        <ul class="dropdown-menu u-rightPopup">
                                            <li>
                                                <%= link_to 'Edit', edit_category_path(category) %>
                                            </li>
                                            <% if can? :destroy, category %>
                                                <li>
                                                    <%= link_to 'Delete', category_path(category), method: :delete, data: { confirm: 'Are you sure?' } %>
                                                </li>
                                            <% end %>
                                        </ul>
                                    </div>
                                </div>
                            </li>
                        <% end %>

                    </ul>
                </li>
            <% end %>
        </ul>
    </div>

    <%= paginate @categories %>
</main>

app/views/categories/new.html.erb
<header class="app-bar promote-layer">
    <div class="app-bar-container">

        <button class="menu"><span class="icon-menu"></span></button>

        <div class="Heading">
            <%= link_to categories_path, class: "Back" do %>
                <span class="icon-chevron-left-thin"></span><span class="Back-text">Back</span>
            <% end %>
            <h1 class="title"><span>New Category</span></h1>
        </div>

        <ul class="app-bar-actions">
            <li>
                <button class="button button--primary" form="_form">Submit</button>
            </li>
        </ul>

    </div>
</header>

<main>
    <div class="Form u-pushTopBottom clear">
        <%= render 'form' %>
        <div class="clear"></div>
    </div>
</main>