config/routes.rb
Rails.application.routes.draw do

  # Route config for ActiveAdmin
  ActiveAdmin.routes(self)

  devise_for :users, skip: [:sessions, :passwords, :registrations, :confirmations, :invitations]

  devise_scope :user do
    post    :forgot_password,   to: "passwords#create",     as: :user_password
    get     :forgot_password,   to: "passwords#new",        as: :new_user_password
    get     :reset_password,    to: "passwords#edit",       as: :edit_user_password
    put     :reset_password,    to: "passwords#update",     as: :reset_user_password

    delete  :logout,            to: "sessions#destroy",     as: :destroy_user_session
    post    :login,             to: "sessions#create",      as: :user_session
    get     :login,             to: "sessions#new",         as: :new_user_session

    post    :signup,            to: "registrations#create",   as: :user_registration
    get     :signup,            to: "registrations#new",      as: :new_user_registration
    get     :profile,           to: "registrations#edit",     as: :edit_user_registration
    put     :profile,           to: "registrations#update",   as: :update_user_registration
    post    :regenerate_api_key,to: "registrations#regenerate_api_key", as: :regenerate_api_key

    post    :activate,          to: "confirmations#create", as: :user_confirmation
    get     :activate,          to: "confirmations#new",    as: :new_user_confirmation
    get     :confirmation,      to: "confirmations#show"

    get     :accept_invitation, to: "invitations#edit",     as: :user_invitation
    put     :accept_invitation, to: "invitations#update"
  end

  resources :users, path: :members do 
    collection do
      post :approve,        action: :approve_user
      post :disapprove,     action: :disapprove_user
      post :grant_admin,    action: :grant_admin
      post :revoke_admin,   action: :revoke_admin
    end
  end

  resources :organizations

  resources :countries do
    resources :sites
  end

  resources :sites
  # Routes for custom methods (for use with ReactJS)
  post "sites/add_role", to: "sites#add_role"
  post "sites/remove_role", to: "sites#remove_role"

  resources :languages do
    resources :articles
  end

  resources :categories

  resources :articles do
    member do
      post :publish
      post :unpublish
    end
  end

  ## API routes
  namespace :api do
    resources :users
    resources :articles
    resources :countries
    resources :categories
    resources :languages
  end

  # You can have the root of your site routed with "root"
  root 'welcome#index'
end

app/models/site.rb
# == Schema Information
#
# Table name: sites
#
#  id         :integer          not null, primary key
#  name       :string
#  country_id :integer
#  created_at :datetime
#  updated_at :datetime
#

class Site < ActiveRecord::Base
  resourcify #This line is added to add Site model as a resource for the Rolify gem. (contributors, volunteers)
  belongs_to :country

  validates :name, presence: true

  # default order when calling the Site model
  default_scope -> { order('created_at DESC') }
end

app/controllers/sites_controller.rb
class SitesController < ApplicationController
  load_and_authorize_resource

  def index
    current_user.organization.countries.each do |a|
      @sites << a.sites
    end
    @sites = @sites.page(params[:page]).per(20)
  end

  def show
    @site = Site.find(params[:id])
    @volunteers = User.with_role :volunteer, @site
    @contributors = User.with_role :contributor, @site
  end

  def new
    if current_user.has_role? :superadmin
      @countries = Country.all
    else
      @countries = current_user.organization.countries
    end

    @site = Site.new
  end

  def edit
    if current_user.has_role? :superadmin
      @countries = Country.all
    else
      @countries = current_user.organization.countries
    end

    @site = Site.find(params[:id])
  end

  def create
    @site = Site.new(site_params)

    if @site.save
      redirect_to @site
    else
      if current_user.has_role? :superadmin
        @countries = Country.all
      else
        @countries = current_user.organization.countries
      end
      render 'new'
    end
  end

  def update
    @site = Site.find(params[:id])

    if @site.update(site_params)
      redirect_to @site
    else
      render 'edit'
    end
  end

  def destroy
    @site = Site.find(params[:id])
    @site.destroy

    redirect_to sites_path
  end


  #####CUSTOM METHODS#####

  #Called from the Sites Show: app/assets/javascripts/components/sites/show.js.jsx.coffee
  # It receives the :username, :site_id, and :act(action) and adds/removes the user as
  # a volunteer/contributor of the given site. It returns the volunteer/contributor list.
  def add_role
    @user = User.where(username: params[:username]).first
    @site = Site.find(params[:site_id])
    action = params[:act]

    if(action == 'volunteer')
      respond_to do |format|
        if @user.add_role :volunteer, @site
          format.json { render json: (User.with_role :volunteer, @site), status: :ok}
        else
          format.json { render json: @user.errors, status: :unprocessable_entity }
        end
      end
    elsif(action == 'contributor')
      respond_to do |format|
        if @user.add_role :contributor, @site
          format.json { render json: (User.with_role :contributor, @site), status: :ok}
        else
          format.json { render json: @user.errors, status: :unprocessable_entity}
        end
      end
    end
  end
  def remove_role
    @user = User.find(params[:user_id])
    @site = Site.find(params[:site_id])
    action = params[:act]

    if(action == 'volunteer')
      respond_to do |format|
        if @user.remove_role :volunteer, @site
          format.json { render json: (User.with_role :volunteer, @site), status: :ok}
        else
          format.json { render json: @user.errors, status: :unprocessable_entity }
        end
      end
    elsif(action == 'contributor')
      respond_to do |format|
        if @user.remove_role :contributor, @site
          format.json { render json: (User.with_role :contributor, @site), status: :ok}
        else
          format.json { render json: @user.errors, status: :unprocessable_entity}
        end
      end
    end
  end

  private
  # Never trust parameters from the scary internet, only allow the white list through.
  def site_params
    params.require(:site).permit(:name, :country_id)
  end
end

app/helpers/sites_helper.rb
module SitesHelper
end

app/views/sites/_form.html.erb
<%= form_for @site, html: {class: "Form--dual", id: "_form"} do |f| %>

    <%= render partial: "shared/error_messages", object: @site %>

    <div class="Form--dualDivider">
        <div class="g--half">

            <div class="Form-group">
                <%= f.label :country_id, "Country" %>
                <%= f.collection_select(:country_id, @countries, :id, :name, {}, {class: "Form-control"})  %>
            </div>

            <div class="Form-group">
                <%= f.label :name, "Site" %>
                <%= f.text_field :name, class: "Form-control" %>
            </div>

        </div>
    </div>
<% end %>

app/views/sites/edit.html.erb
<header class="app-bar promote-layer">
    <div class="app-bar-container">
        <button class="menu"><span class="icon-menu"></span></button>

        <div class="Heading">
            <%= link_to sites_path, class: "Back" do %>
                <span class="icon-chevron-left-thin"></span><span class="Back-text">Back</span>
            <% end %>
            <h1 class="title"><span>Editing Site</span></h1>
        </div>

        <ul class="app-bar-actions">
            <li>
                <button class="button button--primary" form="_form">Submit</button>
            </li>
        </ul>

    </div>
</header>

<main>
    <div class="Form u-pushTopBottom clear">
        <%= render 'form' %>
        <div class="clear"></div>
    </div>
</main>

app/views/sites/index.html.erb
<header class="app-bar promote-layer">
    <div class="app-bar-container">
        <button class="menu"><span class="icon-menu"></span></button>

        <div class="Heading">
            <h1 class="title"><span>Sites</span></h1>
        </div>
    </div>
</header>

<main>
    <div class="AppControls">
        <div class="AppControls--box AppControls-left">
            <form class="Form Form--inline AppControls-search">
                <div class="Form-group">
                    <input type="search" class="Form-control" id="search" placeholder="Search Sites" />
                </div>
                <button type="submit" class="btn btn-default icon-search">Search</button>
            </form>
        </div>

        <div class="AppControls--box AppControls-middle"></div>

        <div class="AppControls--box AppControls-right">
            <a class="button--icontext button--ricontext" href="<%= new_site_path %>"><i class="icon-plus"></i> <span>New Site</span></a>
        </div>
    </div>

    <div class="CardListTable">
        <ul class="CardListTable-body">

            <% @sites.each do |site| %>
                <li>
                    <ul class="CardListTableRow">
                        <li class="CardListTable-cal u-w30px" data-th="#">
                            <div class="CardListTable-content">
                                <%= link_to site.id, site_path(site) %>
                            </div>
                        </li>

                        <li class="CardListTable-cal u-w180px" data-th="Post">
                            <div class="CardListTable-content">
                                <%= site.country.name if site.country %>
                            </div>
                        </li>

                        <li class="CardListTable-cal u-w300px" data-th="Site">
                            <div class="CardListTable-content">
                                <%= site.name %>
                            </div>
                        </li>

                        <% if can? :update, site %>
                            <li class="CardListTable-cal CardListTable-cal--noheading u-w60px tar" data-th="Action">
                                <div class="CardListTable-content">
                                    <div class="dropdown">
                                        <a data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" class="button--icon" href="#"><i class="icon-action"></i></a>
                                        <ul class="dropdown-menu u-rightPopup">
                                            <li>
                                                <%= link_to 'Edit', edit_site_path(site) %>
                                            </li>
                                            <% if can? :destroy, site %>
                                                <li>
                                                    <%= link_to 'Delete', site_path(site), method: :delete, data: { confirm: 'Are you sure?' } %>
                                                </li>
                                            <% end %>
                                        </ul>
                                    </div>
                                </div>
                            </li>
                        <% end %>

                    </ul>
                </li>
            <% end %>
        </ul>
    </div>

    <%= paginate @sites %>
</main>

app/views/sites/new.html.erb
<header class="app-bar promote-layer">
    <div class="app-bar-container">

        <button class="menu"><span class="icon-menu"></span></button>

        <div class="Heading">
            <%= link_to sites_path, class: "Back" do %>
                <span class="icon-chevron-left-thin"></span><span class="Back-text">Back</span>
            <% end %>
            <h1 class="title"><span>New Site</span></h1>
        </div>

        <ul class="app-bar-actions">
            <li>
                <button class="button button--primary" form="_form">Submit</button>
            </li>
        </ul>

    </div>
</header>

<main>
    <div class="Form u-pushTopBottom clear">
        <%= render 'form' %>
        <div class="clear"></div>
    </div>
</main>

app/views/sites/show.html.erb
<%= react_component 'SitesShowBox',
                    {
                            site: @site,
                            country: @site.country,
                            volunteers: @volunteers,
                            contributors: @contributors
                    }%>